describe('Sell page', () => {
  beforeEach(() => {
    cy.visit('/')
    cy.get('.navbar-nav:nth-child(1)')
      .find('.nav-item:nth-child(3)').click()
  })

  it('allows a set of valid selling to be submitted', () => {
    // Fill out web form
    cy.get('#brand').select('Nike')
    cy.get('label').contains('Series').next().type('Air jordan 1 Retro High OG')
    cy.get('label').contains('Name').next().type('Spider-man')
    cy.get('#size').select('38.5')
    cy.get('label').contains('Article').next().type('555088-602')
    cy.get('input[data-test=price]').type(265)
    cy.get('label').contains('Seller').next().type('a600233')
    cy.get('input[data-test=amount]').type(1)
    cy.contains('Selling is on the page!').should('not.exist')
    cy.get('button[type=submit]').click()
    cy.contains('Selling is on the page!').should('exist')
  })
  it('shows error messages for incomplete form fields', () => {
    cy.get('button[type=submit]').click()
    cy.get('.error').contains('Series')
    cy.get('.error').contains('Name')
    cy.get('.error').contains('Art.no')
    cy.get('.error').contains('Seller')
    cy.contains('Please Fill in the Form Correctly.').should('exist')
    cy.get('#brand').select('Nike')
    cy.get('label').contains('Series').next().type('Air jordan 1 Retro High OG')
    cy.get('label').contains('Name').next().type('Not for reselling')
    cy.get('#size').select('38.5')
    cy.get('label').contains('Article').next().type('861428-106')
    cy.get('input[data-test=price]').type(300)
    cy.get('label').contains('Seller').next().type('a600233')
    cy.get('input[data-test=amount]').type(1)
    cy.get('.error').should('not.exist')
  })
})
